### ISSUE TITLE
CRAN release 

### ISSUE THREAD

**Issue by mpadge** [ropensci/mapscanner#38]

**Comment by mpadge** [comment]
> Thanks,
>
> Please do not start the description with "This package", package name, title or similar.
>
> Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g. \value{No return value, called for side effects} or similar)
Missing Rd-tags:
    ms_aggregate_polys.Rd: \value
    ms_rotate_map.Rd: \value
>
> Some code lines in examples are commented out in ms_aggregate_polys.Rd.
Please never do that. Ideally find toy examples that can be regularly executed and checked. Lengthy examples (> 5 sec), can be wrapped in \donttest.
>
> Please ensure that your functions do not write by default or in your examples/vignettes/tests in the user's home filespace (including the package directory and getwd()). This is not allowed by CRAN policies.
In your examples/vignettes/tests you can write to tempdir().
>
> Please make sure that you do not change the user's options, par or working directory. If you really have to do so within functions, please ensure with an *immediate* call of on.exit() that the settings are reset when the function is exited. e.g.:
...
oldpar <- par(no.readonly = TRUE)    # code line i
on.exit(par(oldpar))            # code line i + 1
...
par(mfrow = c (1, 2), mar = c (0, 0, 1, 0))
          # somewhere after
...
>
> e.g.: file-manipulation.R
If you're not familiar with the function, please check ?on.exit. This function makes it possible to restore options before exiting a function even if the function breaks. Therefore it needs to be called immediately after the option change within a function.
>
> Please fix and resubmit.

---

## TODO

- [x] ~~Rm "This package" from Description~~ Doesn't do that anyway!
- [x] Missing `.Rd` value tag for `ms_aggregate_polys`
- [x] Missing `.Rd` value tag for `ms_rotate_map`
- [x] "*Some code lines in examples are commented out in ms_aggregate_polys.Rd.*"
- [x] "*Please ensure that your functions do not write by default ... in the user's home filespace*"
- [x] "*Please make sure that you do not change the user's options, par or working directory*"
